CREATE COLUMN TABLE "EXT"."CS_DEBUG"(
	"TENANTID" VARCHAR(4) NOT NULL,
	"DATETIME" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"OBJECT" VARCHAR(200) NOT NULL,
	"TEXT" VARCHAR(4000),
	"VALUE" INTEGER CS_INT,
	"ID_PROCESO" BIGINT CS_FIXED,
	"LEVEL" VARCHAR(25)
)
UNLOAD PRIORITY 5 AUTO MERGE;