CREATE OR REPLACE PROCEDURE EXT.SMM_SP_ACTUAL_INFORMES_CAT_TVTA(OUT o_salidacontrol VARCHAR(50)
-- ,IN calendar VARCHAR(50)
-- ,IN calendarSeq BIGINT
-- ,IN groupid VARCHAR(50)
,IN i_period VARCHAR(50)
,IN i_periodSeq BIGINT
,IN i_processingUnit VARCHAR(50)
,IN i_processingUnitSeq BIGINT
,IN i_stage VARCHAR(50)
-- ,IN userName VARCHAR(50)
,IN i_triggerFilename VARCHAR(50)
,IN i_informe NVARCHAR(250)
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER 
DEFAULT SCHEMA EXT AS
/* *****************************************************************************
	NAME:       ACTUAL_INFORMES_CAT_TVTA
	PURPOSE:

	REVISIONS:
	Ver      		Date        	Author           	Description
	---------  		----------  	---------------  	-----------------------------------
1.0        11/10/2019  RMF               Created this package.
   
   1.1        11.03.2022  DCR               Nuevo Informe WBE (CAL0124)
   
   1.2        29.03.2022  DCR               Informe Prefactura (CAL0130)
                                            Portada Detalle - Quitar comisiones
                                            
   1.3        19.04.2022  DCR               Inf. Pref. Detalle Campo Producto (CAL0134)
   
   1.4        24.05.2022  DCR               Se añaden Ajustes Manuales a Prefactura Detalle
   
   1.5        20.06.2022  DCR               Se añade Cod. Position a Prefactura Detalle
   
   1.6        14.07.2022  RMM               Se eliminan duplicados en Prefactura 

   1.7        10.01.2023  RMM               Se eliminan el estado liquidado en CAT TVTA ya que no se liquidan por callidus
   
   1.8        15.03.2023  APM               Se añade Fecha actualización en el procedure p_Inf_CAT_TVTA_RESUMEN_PAGO
   
   1.9        12.02.2024  APM               Se añade la llamada al procedure p_Actualiza_Informe_Fecha al final del último
                                            procedura para tener la fecha/hora de la actualización de la última tabla.
                                            
   1.10       15.04.2025  APM               Se añade nuevo filtro en la tabla ENEL_CAT_TVTA_RESUM_PAGO
   
   1.11       16.04.2025  APM               Se comenta el insert a la tabla ENEL_LEADS_CAT_TVTA.
   
   1.12       09.12.2025  APM               Nuevas tablas para informe Balance CAT TVTA E4E
   
   1.13       03.03.2026  APM               Informar tablas para Informe Agrupado de liquidaciones
   
   1.14       19.03.2026  APM               Cambios para Mas Orange
   
   1.15       24.04.2026  APM               Añadir filtros de tipo de crédito en la tabla ENEL_SCAWEB_LIQUIDACION_CAT_TVTA para activación

   1.16       14.05.2026  APM               Se añade filtro en la tabla ENEL_SCAWEB_LIQUIDACION_CAT_TVTA 
   
   1.17       19.05.2026  APM               Se añade filtro en la tabla ENEL_CAT_TVTA_RESUM_PAGO
   
   1.18       20.05.2026  APM               Se quita filtro en la tabla ENEL_INFORME_TRANSACCION
   
   1.19       21.05.2026  APM               Se modifica campo NUM_PEDIDO de la tabla ENEL_E4E_NEGATIVOS_CAT_TVTA y el campo ACTIVIDAD de 
                                            la tabla ENEL_E4E_NEG_TEMP_CAT_TVTA
   2.0										MIGRACIÓN SAP HANA
***************************************************************************** */
BEGIN
DECLARE v_cont INT = 0;
DECLARE v_proc_name NVARCHAR(50) := ::CURRENT_OBJECT_SCHEMA ||'.'|| ::CURRENT_OBJECT_NAME;
DECLARE v_version NVARCHAR(4) := '2.0';
DECLARE v_log_count INTEGER := 0;
DECLARE v_idproceso BIGINT := 0;
DECLARE v_tenantid NVARCHAR(4) := EXT.LIB_GLOBAL_ENDESA:getTenantID();
DECLARE v_permisos_log NVARCHAR(50) := EXT.LIB_GLOBAL_ENDESA:GET_PERMISOS_LOG();
DECLARE v_eot DATE := EXT.LIB_CONSTANTES_ENDESA:v_eot;
DECLARE v_Interfaz_Proceso NVARCHAR(50);
DECLARE v_Interfaz_Activo INT;
DECLARE v_Listado_Informes  NVARCHAR(500);
DECLARE v_i_periodoLiquidado boolean;
DECLARE v_FInicio_Inf timestamp;
DECLARE v_FFin_Inf timestamp;
DECLARE v_i_periodo VARCHAR2(50); --DCR 15.05.2023
DECLARE v_puseq VARCHAR2(50); --DCR 15.05.2023
DECLARE v_contador_debug INT;
DECLARE v_contador_ctrl_inf INT;
DECLARE v_num_ejecucion INT;
DECLARE v_Argumentos INT;



DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name, 'Error en procedimiento principal ' || v_proc_name || ' - SQL_ERROR_MESSAGE: ' || IFNULL(::SQL_ERROR_MESSAGE,'')
																											|| '. SQL_ERROR_CODE: ' || ::SQL_ERROR_CODE, v_log_count, v_idproceso, 'error');
																											
		RESIGNAL;
	END;
	
	CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name, 'Procedure starting for: ' || v_proc_name, v_log_count, v_idproceso,'info');
	CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name, 'Argumentos del proceso: i_period:' || i_period
		|| ' || i_processingUnit: ' || i_processingUnit
		|| ' || i_triggerFilename: ' || i_triggerFilename
		, v_log_count, v_idproceso,'info');
	
	
    --Iniciamos el contador del Debug
    v_contador_debug := 0;
        
    CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Procedure starting...', v_log_count, v_idproceso,'info');
    CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Argumentos del proceso ', v_log_count, v_idproceso,'info');
    -- CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Argumento: calendar             : ['||calendar           ||']', v_log_count, v_idproceso,'info'); 
    -- CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Argumento: calendarSeq          : ['||calendarSeq        ||']', v_log_count, v_idproceso,'info'); 
    -- CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Argumento: groupid              : ['||groupid            ||']', v_log_count, v_idproceso,'info'); 
    -- CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Argumento: i_period               : ['||i_period             ||']', v_log_count, v_idproceso,'info'); 
    -- CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Argumento: i_periodSeq            : ['||i_periodSeq          ||']', v_log_count, v_idproceso,'info'); 
    -- CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Argumento: i_processingUnit       : ['||i_processingUnit     ||']', v_log_count, v_idproceso,'info'); 
    -- CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Argumento: i_processingUnitSeq    : ['||i_processingUnitSeq  ||']', v_log_count, v_idproceso,'info'); 
    -- CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Argumento: i_stage                : ['||i_stage              ||']', v_log_count, v_idproceso,'info'); 
    -- CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Argumento: userName             : ['||userName           ||']', v_log_count, v_idproceso,'info'); 
    -- CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Argumento: i_triggerFilename      : ['||i_triggerFilename    ||']', v_log_count, v_idproceso,'info'); 
    -- CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Argumento: tenantId             : ['||tenantId           ||']', v_log_count, v_idproceso,'info');
    -- CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Argumento: i_informe              : ['||i_informe            ||']', v_log_count, v_idproceso,'info');  
 
	-- BOM - DCR - Gestion Control de Informes 
 
 --------------- Comprobar si es una ejecuci?n por StageHook o manual --------------                                                                                                                                                                                                                                                  
 if  i_triggerFilename = 'EJECUCION_MANUAL' then                                                                                                                                                                                                                                                                                        
  CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Peticion de ejecucion manual con i_periodo ' || i_period, v_log_count, v_idproceso,'info');                                                                                                                                                                                                                                                     
        CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Informes a actualizar  ' || i_informe, v_log_count, v_idproceso,'info');                                                                                                                                                                                                                                                                
        v_Interfaz_Proceso := 'ACTUALIZA_INFORMES_MANUAL';                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                      
  if i_informe = '' or i_informe is null then                                                                                                                                                                                                                                                                                             
            v_Listado_Informes := 'ALL';                                                                                                                                                                                                                                                                                              
            CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Argumento Actualizado : informe : [' || :v_Listado_Informes ||           '] (EJECUCION_MANUAL)', v_log_count, v_idproceso,'info');                                                                                                                                                                                                   
        else                                                                                                                                                                                                                                                                                                                          
            v_Listado_Informes := i_informe;                                                                                                                                                                                                                                                                                            
        end if;                                                                                                                                                                                                                                                                                                                       
 else                                                                                                                                                                                                                                                                                                                                 
        CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Peticion de ejecucion StageHook con i_periodo ' || i_period, v_log_count, v_idproceso,'info');                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                      
	v_Interfaz_Proceso :=
		    CASE
		        WHEN :i_stage = 'Reward__' THEN 'ACTUALIZA_INFORMES_REWARD'
		        WHEN :i_stage = 'Post__'   THEN 'ACTUALIZA_INFORMES_POST'
		        WHEN :i_stage = 'Pay__'    THEN 'ACTUALIZA_INFORMES_PAY'
		        ELSE NULL
		    END;
		    
		IF v_Interfaz_Proceso IS NULL THEN

		    CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG(
		        v_tenantid,
		        v_permisos_log,
		        v_proc_name,
		        'i_stage ' || :i_stage || ' No contemplado. Salimos...',
		        v_log_count,
		        v_idproceso,
		        'info'
		    );
		
		    RETURN;
		
		END IF;                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                      
        SELECT ACTIVO,ARGUMENTOS INTO v_Interfaz_Activo,v_Argumentos DEFAULT 0,0 FROM EXT.SMM_F_INTERFAZ_ACTIVO(:v_Interfaz_Proceso);                                                                                                                                                                                                                                                                                 
        CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Informes a actualizar  ' || v_ARGUMENTOS, v_log_count, v_idproceso,'info');                                                                                                                                                                                                                                                           
        v_Listado_Informes := v_ARGUMENTOS;                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                      
        if v_Interfaz_Activo <> 1 then                                                                                                                                                                                                                                                                                                         
            CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Interfaz '||v_Interfaz_Proceso||' NO ACTIVO. Salimos...', v_log_count, v_idproceso,'info');                                                                                                                                                                                                                                     
            o_salidacontrol :='Salida '||v_Interfaz_Proceso||' no activa.';                                                                                                                                                                                                                                                             
            RETURN;                                                                                                                                                                                                                                                                                                                   
        else                                                                                                                                                                                                                                                                                                                          
            CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Interfaz '||v_Interfaz_Proceso||' ACTIVO.', v_log_count, v_idproceso,'info');                                                                                                                                                                                                                                                   
        end if;                                                                                                                                                                                                                                                                                                                       
 end if;                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                      
    o_salidacontrol :='Procedure '||v_Interfaz_Proceso||' comenzando';                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                      
 --    Se comprueba si el i_periodo Ya ha sido liquidado.                                                                                                                                                                                                                                                                               
    v_i_periodoLiquidado := EXT.SMM_F_COMPROBAR_PERIODO_LIQUIDADO( i_processingUnitSeq, i_period ,i_periodSeq);                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                      
 -- SI EL i_periodO NO SE HA LIQUIDADO, SE EXTRAEN DE NUEVO LOS DATOS PARA LOS INFORMES                                                                                                                                                                                                                                                 
    IF  v_i_periodoLiquidado = false THEN                                                                                                                                                                                                                                                                                               
		------------------------------------------------------------                                                                                                                                                                                                                                                                        
		-- Datos Generales que se usan en varios informes                                                                                                                                                                                                                                                                                   
		------------------------------------------------------------                                                                                                                                                                                                                                                                        
		-- BOM CAL0124 DCR 11.03.22                                                                                                                                                                                                                                                                                                           
        -- Volcar datos de las tablas de transacciones a una tabla temporal. Tabla ENEL_TXN_TEMP                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_TEMPORAL_TXN_TRUNCATE( i_processingUnitSeq, i_period ,i_periodSeq);                                                                                                                                                                                                                                                  
		CALL EXT.SMM_TEMPORAL_TRANSACCIONES( i_processingUnitSeq, i_period ,i_periodSeq);                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                      
        -- Volcar datos de la tabla de creditos a una tabla temporal. Tabla ENEL_CREDIT_TEMP                                                                                                                                                                                                                                          
        CALL EXT.SMM_SP_TEMPORAL_CREDITOS( i_processingUnitSeq, i_period ,i_periodSeq);                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                      
		--BOM APM 09.12.2025                                                                                                                                                                                                                                                                                                                  
        -- Volcar datos de la tabla de incentivos a una tabla temporal. Tabla ENEL_INCEN_TEMP                                                                                                                                                                                                                                         
        CALL EXT.SMM_SP_TEMPORAL_INCENTIVOS( i_processingUnitSeq, i_period ,i_periodSeq);                                                                                                                                                                                                                                                   
		-- EOM APM 09.12.2025                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                      
        -- Volcar datos de Posiciones y participantes a una Temporal de PDS. Tabla: ENEL_PDS_TEMP                                                                                                                                                                                                                                     
        CALL EXT.SMM_SP_TEMPORAL_PDS( i_processingUnitSeq, i_period ,i_periodSeq);                                                                                                                                                                                                                                                          
		-- EOM CAL0124 DCR 11.03.22                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                      
		--Volcar datos de depositos a una tabla temporal ENEL_DEPOSIT_TEMP_CAT_TVTA                                                                                                                                                                                                                                                         
        CALL EXT.SMM_SP_TEMPORAL_DEPOSITOS_CAT_TVTA( i_processingUnitSeq, i_period, i_periodseq);                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                      
		-- Volcar datos de clasificacion a una Temporal de Proveedores. Tabla ENEL_PROVEEDORES_CAT_TVTA                                                                                                                                                                                                                                     
        CALL EXT.SMM_SP_TEMPORAL_PROVEEDORES_CAT_TVTA( i_period ,i_periodSeq);                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                      
		-- Volcar datos de Posiciones y participantes a una Temporal de PDS. Tabla: ENEL_PAYEE_TEMP                                                                                                                                                                                                                                         
        CALL EXT.SMM_SP_TEMPORAL_PAYEE( i_processingUnitSeq, i_period ,i_periodSeq );                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                      
		-- Volcar datos de Productos a una Temporal Tabla ENEL_PRODUCTOS_TEMP                                                                                                                                                                                                                                                               
        CALL EXT.SMM_SP_TEMPORAL_PRODUCTOS_CAT_TVTA( i_period ,i_periodSeq);                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_TEMPORAL_E4E_NEGATIVOS_CAT_TVTA( i_period ,i_periodSeq ,i_processingUnitSeq  );                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                      
        IF EXT.SMM_F_EXISTE_INFORME_EN_LISTA('E4E', v_Listado_Informes) = 1 THEN                                                                                                                                                                                                                                                                     
			-- Volcar datos de clasificaci?n a una Temporal de Contratos.     Tabla ENEL_E4E_CONTRATOS_TEMP                                                                                                                                                                                                                                    
			CALL EXT.SMM_SP_TEMPORAL_CONTRATOS_E4E_CAT_TVTA( i_period ,i_periodSeq);                                                                                                                                                                                                                                                                        
			                                                                                                                                                                                                                                                                                                                                    
			-- Extraer datos de Dep?sitos y JOIN con tablas temporales Tabla: ENEL_E4E_DEPOSIT_TEMP                                                                                                                                                                                                                                            
			CALL EXT.SMM_SP_TEMPORAL_DEPOSITOS_E4E_CAT_TVTA( i_processingUnitSeq, i_period ,i_periodSeq);                                                                                                                                                                                                                                                       
			                                                                                                                                                                                                                                                                                                                                    
			-- Extraer datos de TEMP_Depositos. Tabla: ENEL_E4E_FINAL Fichero 1                                                                                                                                                                                                                                                                
			CALL EXT.SMM_SP_FINAL_E4E_1_CAT_TVTA( i_period ,i_periodSeq);                                                                                                                                                                                                                                                                                   
			                                                                                                                                                                                                                                                                                                                                    
			-- Extraer datos de TEMP_Depositos. Tabla: ENEL_E4E_FINAL Fichero 2                                                                                                                                                                                                                                                                
			CALL EXT.SMM_SP_FINAL_E4E_2_CAT_TVTA( i_period ,i_periodSeq);                                                                                                                                                                                                                                                                                   
			                                                                                                                                                                                                                                                                                                                                    
			-- Actualizamos la fecha del informes en la tabla                                                                                                                                                                                                                                                                                  
			CALL EXT.SMM_SP_ACTUALIZA_INFORME_FECHA( i_period, 'E4E CAT TVTA');                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                      
		  if v_Interfaz_Proceso = 'ACTUALIZA_INFORMES_REWARD' THEN  -- v2.4                                                                                                                                                                                                                                                                  
		    -- Los datos Negativos solo se extraen enel REWARD                                                                                                                                                                                                                                                                                
		    -- Extraer datos NEGATIVOS de TEMP_Depositos. Tabla: ENEL_E4E_NEGATIVOS                                                                                                                                                                                                                                                           
		    CALL EXT.SMM_SP_FINAL_E4E_NEGATIVOS_CAT_TVTA( i_processingUnitSeq, i_period ,i_periodSeq);                                                                                                                                                                                                                                                       
		                                                                                                                                                                                                                                                                                                                                      
		    -- Actualizamos la fecha del informe en la tabla                                                                                                                                                                                                                                                                                  
		    CALL EXT.SMM_SP_ACTUALIZA_INFORME_FECHA( i_period, 'E4ENEG CAT TVTA');                                                                                                                                                                                                                                                                           
		  end if;                                                                                                                                                                                                                                                                                                                            
		                                                                                                                                                                                                                                                                                                                                      
		   --Generamos datos de resumen de pagos                                                                                                                                                                                                                                                                                              
		   CALL EXT.SMM_SP_INFORME_RESUMEN_PAGOS( i_processingUnitSeq, i_period ,i_periodSeq);                                                                                                                                                                                                                                                     
		end if;                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                      
/* BOM CAL0130 DCR 29.03.22 */                                                                                                                                                                                                                                                                                                        
/* Old                                                                                                                                                                                                                                                                                                                                
        p_Inf_CAT_TVTA_IB_TEMP ( i_processingUnitSeq, i_period, i_periodSeq , tenantId , v_Interfaz_Proceso );                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                      
        p_Inf_CAT_TVTA_RESUM_PAGO_TEMP ( i_processingUnitSeq, i_period, i_periodSeq , tenantId , v_Interfaz_Proceso );                                                                                                                                                                                                                      
*/                                                                                                                                                                                                                                                                                                                                    
        CALL EXT.SMM_SP_INF_CAT_TVTA_RESUMEN_PAGO( i_processingUnitSeq, i_period, i_periodSeq , v_Interfaz_Proceso );                                                                                                                                                                                                                         
        --BOM APM 15.03.2023                                                                                                                                                                                                                                                                                                          
        -- Actualizamos la fecha del informe en la tabla                                                                                                                                                                                                                                                                              
        CALL EXT.SMM_SP_ACTUALIZA_INFORME_FECHA( i_period, 'CAT_TVTA_RESUMEN');                                                                                                                                                                                                                                                                      
        --EOM APM 15.03.2023                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_INF_CAT_TVTA_APORTE_TEMP( i_processingUnitSeq, i_period, i_periodSeq, v_Interfaz_Proceso );                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_INF_CAT_TVTA_APORTE ( i_processingUnitSeq, i_period, i_periodSeq, v_Interfaz_Proceso );                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_INF_CAT_TVTA_AM_TEMP ( i_processingUnitSeq, i_period, i_periodSeq, v_Interfaz_Proceso );                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_INF_CAT_TVTA_AM ( i_processingUnitSeq, i_period, i_periodSeq, v_Interfaz_Proceso );                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_INF_CAT_TVTA_BONUSMALUS_TEMP ( i_processingUnitSeq, i_period , i_periodSeq  , v_Interfaz_Proceso );                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_INF_CAT_TVTA_BONUS_MALUS ( i_processingUnitSeq, i_period , i_periodSeq  , v_Interfaz_Proceso );                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_INF_CAT_TVTA_INCENPENAL_TEMP ( i_processingUnitSeq , i_period, i_periodSeq, v_Interfaz_Proceso );                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_INF_CAT_TVTA_INCEN_PENAL ( i_processingUnitSeq , i_period, i_periodSeq, v_Interfaz_Proceso );                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_INF_CAT_TVTA_IP_TOTAL_TEMP ( i_processingUnitSeq, i_periodSeq, v_Interfaz_Proceso );                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_INF_CAT_TVTA_IP_TOTAL ( i_period, v_Interfaz_Proceso );                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_INF_CAT_TVTA_IP_VENTA_TEMP ( i_processingUnitSeq , i_periodseq  , v_Interfaz_Proceso );                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_INF_CAT_TVTA_IP_VENTA ( i_period , v_Interfaz_Proceso );                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_INF_FACTURA_CAT_TVTA_DETALLE ( i_processingUnitSeq , i_period , i_periodSeq , v_Interfaz_Proceso );                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_INF_FACTURA_CAT_TVTA_PORTADA ( i_period );                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_INF_FACTURA_CAT_TVTA_DEPO (i_periodSeq);                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                      
        CALL EXT.SMM_SP_INFORME_TRANSACCION( i_processingUnitSeq , i_period , i_periodSeq  );                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                      
-- BOM CAL0124 DCR 11.03.22                                                                                                                                                                                                                                                                                                           
        -- Extraer datos para Interface de LIQUIDACION MENSUAL SCAWEB  (Captacion - Importe Base)                                                                                                                                                                                                                                     
        CALL EXT.SMM_SP_INFORME_LIQSCAWEB_CAT_TVTA (i_processingUnitSeq, i_period ,i_periodSeq  , v_Interfaz_Proceso );                                                                                                                                                                                                                                  
        CALL EXT.SMM_SP_RAPPELES_CAT_TVTA( i_period ,i_periodSeq  , v_Interfaz_Proceso );                                                                                                                                                                                                                                                             
-- EOM CAL0124 DCR 11.03.22                                                                                                                                                                                                                                                                                                           
--BOM APM 12.02.2024                                                                                                                                                                                                                                                                                                                  
        -- Actualizamos la fecha del informe                                                                                                                                                                                                                                                                                          
        CALL EXT.SMM_SP_ACTUALIZA_INFORME_FECHA( i_period, 'INF_CUADRE_LIQ');                                                                                                                                                                                                                                                                        
--EOM APM 12.02.2024                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                      
--BOM APM 09.12.2025                                                                                                                                                                                                                                                                                                                  
        IF EXT.SMM_F_EXISTE_INFORME_EN_LISTA('SCAWEB', v_Listado_Informes) = 1 THEN                                                                                                                                                                                                                                                                  
             -- Extraer datos de creditos calculados para el i_periodo -> Tabla : ENEL_SCAWEB_LIQUIDACION                                                                                                                                                                                                                               
             CALL EXT.SMM_SP_TEMPORAL_CREDITOS_SCAWEB_CAT_TVTA( i_processingUnitSeq, i_period ,i_periodSeq);                                                                                                                                                                                                                                         
             -- Actualizamos la fecha del informes en la tabla                                                                                                                                                                                                                                                                        
            CALL EXT.SMM_SP_ACTUALIZA_INFORME_FECHA( i_period, 'SCAWEB');                                                                                                                                                                                                                                                                            
        end if;                                                                                                                                                                                                                                                                                                                       
        -- Comparativa Pagos solo se hace si se ejecutan todos los informes                                                                                                                                                                                                                                                           
        IF v_Listado_Informes = 'ALL' THEN                                                                                                                                                                                                                                                                                            
            CALL EXT.SMM_SP_COMPARATIVA_PAGOS_SCAWEB_E4E_CAT_TVTA( i_processingUnitSeq, i_period ,i_periodSeq);                                                                                                                                                                                                                                       
            CALL EXT.SMM_SP_ACTUALIZA_INFORME_FECHA( i_period, 'SCAWEB_E4E_CAT_TVTA');                                                                                                                                                                                                                                                               
        end if;                                                                                                                                                                                                                                                                                                                       
--EOM APM 09.12.2025                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                      
--BOM APM 03.03.2026                                                                                                                                                                                                                                                                                                                  
            ---------------------------------------------------                                                                                                                                                                                                                                                                       
            -- Datos para Informe Agrupado de liquidaciones                                                                                                                                                                                                                                                                           
            ---------------------------------------------------                                                                                                                                                                                                                                                                       
            IF EXT.SMM_F_EXISTE_INFORME_EN_LISTA('LIQ_CAT_TVTA', v_Listado_Informes) = 1 THEN                                                                                                                                                                                                                                                        
    CALL EXT.SMM_SP_INFORME_AGRUPADO(i_processingUnitSeq, i_period ,i_periodSeq, v_Interfaz_Proceso );                                                                                                                                                                                                                                       
    -- Actualizamos la fecha del informes en la tabla                                                                                                                                                                                                                                                                                 
    CALL EXT.SMM_SP_ACTUALIZA_INFORME_FECHA ( i_period, 'LIQ_CAT_TVTA');                                                                                                                                                                                                                                                                              
  end if;                                                                                                                                                                                                                                                                                                                            
--EOM APM 03.03.2026                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                      
    END IF;                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                      
    CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Procedure ' || v_proc_name  ||' Ending...', v_log_count, v_idproceso,'info');                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

END