CREATE OR REPLACE PROCEDURE EXT.SMM_SP_TEMPORAL_E4E_NEGATIVOS_CAT_TVTA( i_period VARCHAR(25), IN i_periodseq BIGINT, IN i_processingunitseq BIGINT)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER 
DEFAULT SCHEMA EXT AS
/*---------------------------------------------------------------------
    | Author: Samuel Miralles Manresa
    | Company: Inycom
    | Initial Version Date: 
    |----------------------------------------------------------------------
    | Procedure Purpose: 
    |
	| Version:	0.1	SMM	   Initial Version.
	|
    -----------------------------------------------------------------------
*/
BEGIN
    DECLARE v_cont INT = 0;
	DECLARE v_proc_name NVARCHAR(50) := ::CURRENT_OBJECT_SCHEMA ||'.'|| ::CURRENT_OBJECT_NAME;
	DECLARE v_version NVARCHAR(4) := '0.1';
	DECLARE v_log_count INTEGER := 0;
	DECLARE v_idproceso BIGINT := 0;
	DECLARE v_tenantid NVARCHAR(4) := EXT.LIB_GLOBAL_ENDESA:getTenantID();
	DECLARE v_permisos_log NVARCHAR(50) := EXT.LIB_GLOBAL_ENDESA:GET_PERMISOS_LOG();
	DECLARE v_eot DATE := EXT.LIB_CONSTANTES_ENDESA:v_eot;
	DECLARE v_finicio TIMESTAMP = CURRENT_TIMESTAMP;
	DECLARE v_contador_ctrl_inf INT;
	DECLARE v_num_ejecucion INT;
	DECLARE v_ultimo_dia_periodo DATE;
	

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name, 'Error en procedimiento principal ' || v_proc_name || ' - SQL_ERROR_MESSAGE: ' || IFNULL(::SQL_ERROR_MESSAGE,'')
																											|| '. SQL_ERROR_CODE: ' || ::SQL_ERROR_CODE, v_log_count, v_idproceso, 'error');
		-- CALL EXT.SMM_SP_Z_CTRL_INF(v_contador_ctrl_inf, v_num_ejecucion, v_proc_name, v_finicio, current_timestamp, 'Error:'||::SQL_ERROR_CODE||::SQL_ERROR_MESSAGE);																									
																							
		RESIGNAL;
	END;
	
	-- v_ultimo_dia_periodo := EXT.SMM_F_ULTIMO_DIA_PERIODO(i_periodseq);
	
	CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name, 'Procedure starting for: ' || v_proc_name, v_log_count, v_idproceso,'info');
	CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name, 'Argumentos del proceso: ' 
		|| ' || i_processingunitseq: ' || i_processingunitseq
		|| ' || i_period: ' || i_period
		|| ' || i_periodseq: ' || i_periodseq
		, v_log_count, v_idproceso,'info');
	
	CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Inicio Truncado de la tabla SMM_E4E_NEG_TEMP_CAT_TVTA.', v_log_count, v_idproceso,'info');                                                                                                                                                                                                                                                  
    DELETE FROM EXT.SMM_E4E_NEG_TEMP_CAT_TVTA WHERE PERIODO = i_period;                                                                                                                                                                                                                                                              
    CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Fin Truncado de la tabla SMM_E4E_NEG_TEMP_CAT_TVTA.', v_log_count, v_idproceso,'info');                                                                                                                                                                                                                                                  
    
    v_ultimo_dia_periodo := EXT.SMM_F_ULTIMO_DIA_PERIODO(i_periodseq);
                                                                                                                                                                                                                                                                                                                                      
    CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Origen de ENEL_E4E_NEG_TEMP_CAT_TVTA : CS_DEPOSIT.', v_log_count, v_idproceso,'info');                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                      
	INSERT INTO EXT.SMM_E4E_NEG_TEMP_CAT_TVTA(    PERIODSEQ,PERIODO, DEPOSITSEQ,POSITIONSEQ,PAYEESEQ,VALUE,POS_NAME,                                                                                                                                                                                                                
                                                PAR_PROVEEDOR,NOMBRE_FISCAL, CIF, TIPO_IMPOSITIVO,COD_CONTRATO,POS_DOC,                                                                                                                                                                                                               
                                                TEXTO_BREVE,ORG_COMPRAS,CODIGO_SERVICIO, IDPROVEEDOR, FICHERO, SOCIEDAD,CECO,                                                                                                                                                                                                         
                                                DESCRIPCION,GR_COMPRAS,CENTRO_LOGISTICO,WBE_FINAL_IMPUTACION, ACTIVIDAD, DETALLE_ACTIVIDAD, TIPO_PAGO,                                                                                                                                                                                
                                                POS_FECHA_INI_VIGENCIA, VALOR_OPERACIONES, CODIGODEUDOR,COMUNIDAD_AUTONOMA, ORG_VENTAS,CONDICIONES_PAGO, SUBPOSICION, ID_CENTRO_E4E, BUSINESSUNIT  )                                                                                                                                  
	Select                                                                                                                                                                                                                                                                                                                               
	 DEPO.PERIODSEQ,                                                                                                                                                                                                                                                                                                                     
	 DEPO.PERIODO,                                                                                                                                                                                                                                                                                                                       
	 MAX(DEPO.DEPOSITSEQ), -- Guardamos la ref. del seq deposito maximo                                                                                                                                                                                                                                                                  
	 DEPO.POSITIONSEQ,                                                                                                                                                                                                                                                                                                                   
	 DEPO.PAYEESEQ,                                                                                                                                                                                                                                                                                                                      
	 ROUND(sum(DEPO.VALUE),2),                                                                                                                                                                                                                                                                                                           
	 -- TMP_PDS.PAYEEID,                                                                                                                                                                                                                                                                                                                 
	 TMP_PAYEE.POS_NAME,                                                                                                                                                                                                                                                                                                                 
	 TMP_PAYEE.PAR_PROVEEDOR,                                                                                                                                                                                                                                                                                                            
	 TMP_PAYEE.NOMBRE_FISCAL,                                                                                                                                                                                                                                                                                                            
	 TMP_PAYEE.CIF,                                                                                                                                                                                                                                                                                                                      
	 TMP_PAYEE.TIPO_IMPOSITIVO,                                                                                                                                                                                                                                                                                                          
	 TMP_CONTRA.COD_CONTRATO,                                                                                                                                                                                                                                                                                                            
	 TMP_CONTRA.POS_DOC,                                                                                                                                                                                                                                                                                                                 
	 TMP_CONTRA.TEXTO_BREVE,                                                                                                                                                                                                                                                                                                             
	 TMP_CONTRA.ORG_COMPRAS,                                                                                                                                                                                                                                                                                                             
	 TMP_CONTRA.CODIGO_SERVICIO,                                                                                                                                                                                                                                                                                                         
	 TMP_PROV.IDPROVEEDOR,                                                                                                                                                                                                                                                                                                               
	 TMP_PROV.FICHERO,                                                                                                                                                                                                                                                                                                                   
	 TMP_PROV.SOCIEDAD,                                                                                                                                                                                                                                                                                                                  
	 TMP_PROV.CECO,                                                                                                                                                                                                                                                                                                                      
	 TMP_PROV.DESCRIPCION,                                                                                                                                                                                                                                                                                                               
	 TMP_PROV.GR_COMPRAS,                                                                                                                                                                                                                                                                                                                
	 TMP_PROV.CENTRO_LOGISTICO,                                                                                                                                                                                                                                                                                                          
	 DEPO.EARNINGGROUPID,                                                                                                                                                                                                                                                                                                                
	       /*BOM APM 21.05.2026 Old Code*/                                                                                                                                                                                                                                                                                               
	 --TMP_PROV.ACTIVIDAD,                                                                                                                                                                                                                                                                                                               
	       --New Code                                                                                                                                                                                                                                                                                                                    
	       DEPO.GENERICATTRIBUTE1,                                                                                                                                                                                                                                                                                                       
	       /*EOM APM 21.05.2026*/                                                                                                                                                                                                                                                                                                        
	 TMP_PROV.DETALLE_ACTIVIDAD,                                                                                                                                                                                                                                                                                                         
	 DEPO.tipo_pago_ga5, --------------                                                                                                                                                                                                                                                                                                  
	 TMP_PAYEE.FECHA_INI_VIGENCIA,                                                                                                                                                                                                                                                                                                       
	 0 as VALOR_OPERACIONES,                                                                                                                                                                                                                                                                                                             
	 TMP_PAYEE.CODIGODEUDOR,                                                                                                                                                                                                                                                                                                             
	 TMP_PAYEE.COMUNIDAD_AUTONOMA,                                                                                                                                                                                                                                                                                                       
	 TMP_PROV.ORG_VENTAS,                                                                                                                                                                                                                                                                                                                
	 TMP_CONTRA.CONDICIONES_PAGO,                                                                                                                                                                                                                                                                                                        
	 TMP_CONTRA.SUBPOSICION,                                                                                                                                                                                                                                                                                                             
	 TMP_PAYEE.ID_CENTRO_E4E,                                                                                                                                                                                                                                                                                                            
	 CASE BU.NAME                                                                                                                                                                                                                                                                                                                        
	  WHEN 'ENDESA OPV' THEN 'EOPV'                                                                                                                                                                                                                                                                                                      
	  WHEN 'CCPP Comercializacion' THEN 'CCPP'                                                                                                                                                                                                                                                                                           
	  WHEN 'ALICO' THEN 'ALIC'                                                                                                                                                                                                                                                                                                           
	  WHEN 'Endesa X' THEN 'ENDX'                                                                                                                                                                                                                                                                                                        
	  WHEN 'CAT TVTA' THEN 'CATT'                                                                                                                                                                                                                                                                                                        
	  WHEN 'Administracion Callidus' THEN 'ADMC'                                                                                                                                                                                                                                                                                         
	  ELSE BU.NAME                                                                                                                                                                                                                                                                                                                       
	 END AS BUSINESS_UNIT                                                                                                                                                                                                                                                                                                                
	                                                                                                                                                                                                                                                                                                                                     
	FROM EXT.SMM_DEPOSIT_TEMP_CAT_TVTA DEPO                                                                                                                                                                                                                                                                                                 
	 INNER JOIN EXT.SMM_PAYEE_TEMP_CAT_TVTA TMP_PAYEE                                                                                                                                                                                                                                                                                       
	  ON DEPO.payeeseq=TMP_PAYEE.payeeseq                                                                                                                                                                                                                                                                                                
	  and DEPO.POSITIONSEQ=TMP_PAYEE.RULEELEMENTOWNERSEQ                                                                                                                                                                                                                                                                                 
	  and DEPO.periodseq=TMP_PAYEE.periodseq                                                                                                                                                                                                                                                                                             
	  AND TMP_PAYEE.PROCESSINGUNITSEQ = i_processingUnitSeq                                                                                                                                                                                                                                                                               
	                                                                                                                                                                                                                                                                                                                                     
	 INNER JOIN EXT.SMM_PROVEEDORES_TEMP_CAT_TVTA TMP_PROV                                                                                                                                                                                                                                                                                  
	  ON TMP_PROV.IDPROVEEDOR=DEPO.PROVEEDOR_GA6                                                                                                                                                                                                                                                                                         
	  AND DEPO.periodseq=TMP_PROV.periodseq                                                                                                                                                                                                                                                                                              
	                                                                                                                                                                                                                                                                                                                                     
	 --INNER JOIN ENEL_E4E_CONTRATOS_TEMP TMP_CONTRA                                                                                                                                                                                                                                                                                     
	 LEFT JOIN EXT.SMM_E4E_CONTRA_TEMP_CAT_TVTA TMP_CONTRA                                                                                                                                                                                                                                                                                  
	  ON TMP_CONTRA.periodseq=DEPO.periodseq                                                                                                                                                                                                                                                                                             
	  AND TMP_CONTRA.POS_NAME = TMP_PAYEE.POS_NAME                                                                                                                                                                                                                                                                                       
	  AND TMP_CONTRA.ACTIVIDAD_DETALLADA=TMP_PROV.DETALLE_ACTIVIDAD                                                                                                                                                                                                                                                                      
	  AND TMP_CONTRA.periodseq=TMP_PROV.periodseq                                                                                                                                                                                                                                                                                        
	                                                                                                                                                                                                                                                                                                                                     
	 INNER JOIN CS_BUSINESSUNIT BU                                                                                                                                                                                                                                                                                                       
	  ON DEPO.BUSINESSUNITMAP = BU.MASK                                                                                                                                                                                                                                                                                                  
	                                                                                                                                                                                                                                                                                                                                     
	WHERE                                                                                                                                                                                                                                                                                                                                
	 DEPO.TENANTID = v_tenantid                                                                                                                                                                                                                                                                                                           
	 AND DEPO.periodseq=i_periodseq                                                                                                                                                                                                                                                                                                       
	 AND DEPO.PROCESSINGUNITSEQ =  i_processingUnitSeq                                                                                                                                                                                                                                                                                    
	 --AND DEPO.VALUE < 0 --APM 21.05.2026 Se comenta. --DMS 20.05.2026 Se descomenta.                                                                                                                                                                                                                                                   
	                                                                                                                                                                                                                                                                                                                                     
	GROUP BY                                                                                                                                                                                                                                                                                                                             
	 DEPO.PERIODSEQ,                                                                                                                                                                                                                                                                                                                     
	 DEPO.PERIODO,                                                                                                                                                                                                                                                                                                                       
	 DEPO.POSITIONSEQ,                                                                                                                                                                                                                                                                                                                   
	 DEPO.PAYEESEQ,                                                                                                                                                                                                                                                                                                                      
	 TMP_PAYEE.POS_NAME,                                                                                                                                                                                                                                                                                                                 
	 TMP_PAYEE.PAR_PROVEEDOR,                                                                                                                                                                                                                                                                                                            
	 TMP_PAYEE.NOMBRE_FISCAL,                                                                                                                                                                                                                                                                                                            
	 TMP_PAYEE.CIF,                                                                                                                                                                                                                                                                                                                      
	 TMP_PAYEE.TIPO_IMPOSITIVO,                                                                                                                                                                                                                                                                                                          
	 TMP_CONTRA.COD_CONTRATO,                                                                                                                                                                                                                                                                                                            
	 TMP_CONTRA.POS_DOC,                                                                                                                                                                                                                                                                                                                 
	 TMP_CONTRA.TEXTO_BREVE,                                                                                                                                                                                                                                                                                                             
	 TMP_CONTRA.ORG_COMPRAS,                                                                                                                                                                                                                                                                                                             
	 TMP_CONTRA.CODIGO_SERVICIO,                                                                                                                                                                                                                                                                                                         
	 TMP_PROV.IDPROVEEDOR,                                                                                                                                                                                                                                                                                                               
	 TMP_PROV.FICHERO,                                                                                                                                                                                                                                                                                                                   
	 TMP_PROV.SOCIEDAD,                                                                                                                                                                                                                                                                                                                  
	 TMP_PROV.CECO,                                                                                                                                                                                                                                                                                                                      
	 TMP_PROV.DESCRIPCION,                                                                                                                                                                                                                                                                                                               
	 TMP_PROV.GR_COMPRAS,                                                                                                                                                                                                                                                                                                                
	 TMP_PROV.CENTRO_LOGISTICO,                                                                                                                                                                                                                                                                                                          
	 DEPO.EARNINGGROUPID,                                                                                                                                                                                                                                                                                                                
	       /*BOM APM 21.05.2026 Old Code*/                                                                                                                                                                                                                                                                                               
	 --TMP_PROV.ACTIVIDAD,                                                                                                                                                                                                                                                                                                               
	       --New Code                                                                                                                                                                                                                                                                                                                    
	       DEPO.GENERICATTRIBUTE1,                                                                                                                                                                                                                                                                                                       
	       /*EOM APM 21.05.2026*/                                                                                                                                                                                                                                                                                                        
	 TMP_PROV.DETALLE_ACTIVIDAD,                                                                                                                                                                                                                                                                                                         
	 DEPO.TIPO_PAGO_GA5,                                                                                                                                                                                                                                                                                                                 
	 TMP_PAYEE.FECHA_INI_VIGENCIA,                                                                                                                                                                                                                                                                                                       
	 TMP_PAYEE.CODIGODEUDOR,                                                                                                                                                                                                                                                                                                             
	 TMP_PAYEE.COMUNIDAD_AUTONOMA,                                                                                                                                                                                                                                                                                                       
	 TMP_PROV.ORG_VENTAS,                                                                                                                                                                                                                                                                                                                
	 TMP_CONTRA.CONDICIONES_PAGO,                                                                                                                                                                                                                                                                                                        
	 TMP_CONTRA.SUBPOSICION,                                                                                                                                                                                                                                                                                                             
	 TMP_PAYEE.ID_CENTRO_E4E,                                                                                                                                                                                                                                                                                                            
	 BU.NAME                                                                                                                                                                                                                                                                                                                             
	 HAVING SUM(DEPO.VALUE) < 0                                                                                                                                                                                                                                                                                                          
	;                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                          
 COMMIT;                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                      
    CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name,'Fin Carga de la tabla SMM_E4E_NEGATIVOS_TEMP_CAT_TVTA: '|| ::ROWCOUNT || ' filas.', v_log_count, v_idproceso,'info');                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                      
        
      
    


    
  

	-- CALL EXT.SMM_SP_Z_CTRL_INF(v_contador_ctrl_inf, v_num_ejecucion, v_proc_name, v_finicio, current_timestamp, NULL);
	
	
	CALL LIB_GLOBAL_ENDESA:WRITE_DEBUG(v_tenantid,v_permisos_log, v_proc_name, 'Fin procedimiento', v_log_count, v_idproceso, 'info');
end;