CREATE OR REPLACE PROCEDURE EXT.SMM_TEMPORAL_TRANSACCIONES( IN i_processingunitseq BIGINT, i_period VARCHAR(25), IN i_periodseq BIGINT)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER 
DEFAULT SCHEMA EXT AS
/*---------------------------------------------------------------------
    | Author: Samuel Miralles Manresa
    | Company: Inycom
    | Initial Version Date: 
    |----------------------------------------------------------------------
    | Procedure Purpose: 
    |
	| Version:	0.1	SMM	   Initial Version.
	|
    -----------------------------------------------------------------------
*/
BEGIN
    DECLARE v_cont INT = 0;
	DECLARE v_proc_name NVARCHAR(50) := ::CURRENT_OBJECT_SCHEMA ||'.'|| ::CURRENT_OBJECT_NAME;
	DECLARE v_version NVARCHAR(4) := '0.1';
	DECLARE v_log_count INTEGER := 0;
	DECLARE v_idproceso BIGINT := 0;
	DECLARE v_tenantid NVARCHAR(4) := EXT.LIB_GLOBAL_ENDESA:getTenantID();
	DECLARE v_permisos_log NVARCHAR(50) := EXT.LIB_GLOBAL_ENDESA:GET_PERMISOS_LOG();
	DECLARE v_eot DATE := EXT.LIB_CONSTANTES_ENDESA:v_eot;
	DECLARE v_finicio TIMESTAMP = CURRENT_TIMESTAMP;
	DECLARE v_contador_ctrl_inf INT;
	DECLARE v_num_ejecucion INT;
	DECLARE v_periodstartdate DATE;
	DECLARE v_periodenddate DATE;
	
	

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name, 'Error en procedimiento principal ' || v_proc_name || ' - SQL_ERROR_MESSAGE: ' || IFNULL(::SQL_ERROR_MESSAGE,'')
																											|| '. SQL_ERROR_CODE: ' || ::SQL_ERROR_CODE, v_log_count, v_idproceso, 'error');
		-- CALL EXT.SMM_SP_Z_CTRL_INF(v_contador_ctrl_inf, v_num_ejecucion, v_proc_name, v_finicio, current_timestamp, 'Error:'||::SQL_ERROR_CODE||::SQL_ERROR_MESSAGE);																									
																							
		RESIGNAL;
	END;
	
	-- v_ultimo_dia_periodo := EXT.SMM_F_ULTIMO_DIA_PERIODO(i_periodseq);
	
	CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name, 'Procedure starting for: ' || v_proc_name, v_log_count, v_idproceso,'info');
	CALL EXT.LIB_GLOBAL_ENDESA:WRITE_DEBUG (v_tenantid,v_permisos_log, v_proc_name, 'Argumentos del proceso: ' 
		|| ' || i_processingunitseq: ' || i_processingunitseq
		|| ' || i_period: ' || i_period
		|| ' || i_periodseq: ' || i_periodseq
		, v_log_count, v_idproceso,'info');
	
	INSERT INTO EXT.SMM_TXN_TEMP( TENANTID, PERIODSEQ, PERIODO, SALESORDERSEQ, SALESTRANSACTIONSEQ, ORDERID, LINENUMBER, SUBLINENUMBER, EVENTYPEID, COMPENSATIONDATE,                                                                                                                                                            
          ACCOUNTINGDATE, PRODUCTID, GENERICATTRIBUTE1, GENERICATTRIBUTE2, GENERICATTRIBUTE3, GENERICATTRIBUTE4, GENERICATTRIBUTE5, GENERICATTRIBUTE6,                                                                                                                                                                                
          GENERICATTRIBUTE7, GENERICATTRIBUTE8, GENERICATTRIBUTE9, GENERICATTRIBUTE10, GENERICATTRIBUTE11, GENERICATTRIBUTE12, GENERICATTRIBUTE13,                                                                                                                                                                                    
          GENERICATTRIBUTE14, GENERICATTRIBUTE15, GENERICATTRIBUTE16, GENERICATTRIBUTE17, GENERICATTRIBUTE18,GENERICATTRIBUTE19, GENERICATTRIBUTE20,                                                                                                                                                                                  
                                        GENERICATTRIBUTE21, GENERICNUMBER1, GENERICNUMBER2, GENERICNUMBER3, GENERICDATE3, GENERICDATE4, GENERICDATE5, GENERICBOOLEAN2,                                                                                                                                                                
                                        PONUMBER, DATASOURCE, TAD_ADDRESS1, TAD_CITY, TAD_STATE, TAD_POSTALCODE, TAD_INDUSTRY, TAD_GEOGRAPHY, TAS_POSITIONNAME,                                                                                                                                                                       
          TAS_GENERICATTRIBUTE1, TAS_GENERICATTRIBUTE2, TAS_GENERICNUMBER1, TAS_GENERICNUMBER2, TEX0_GENERICATTRIBUTE4, TEX0_GENERICATTRIBUTE5,                                                                                                                                                                                       
          TEX0_GENERICATTRIBUTE6, TEX0_GENERICATTRIBUTE7, TEX0_GENERICATTRIBUTE8, TEX0_GENERICATTRIBUTE9, TEX0_GENERICATTRIBUTE10,                                                                                                                                                                                                    
          TEX0_GENERICATTRIBUTE11, TEX0_GENERICATTRIBUTE12, TEX0_GENERICATTRIBUTE13, TEX0_GENERICATTRIBUTE14, TEX0_GENERICATTRIBUTE15,                                                                                                                                                                                                
                                        TEX0_GENERICATTRIBUTE16, TEX0_GENERICATTRIBUTE17, TEX0_GENERICDATE3, TEX0_GENERICDATE4, TEX0_GENERICBOOLEAN1,                                                                                                                                                                                 
                                        TEX0_GENERICNUMBER1, TEX0_GENERICNUMBER2, TEX0_GENERICNUMBER3, TEX0_GENERICNUMBER4, TEX0_GENERICNUMBER5,PROCESSINGUNITSEQ,                                                                                                                                                                    
          ALTERNATEORDERNUMBER, GENERICATTRIBUTE24, TEX0_GENERICATTRIBUTE3)                                                                                                                                                                                                                                                           
    SELECT                                                                                                                                                                                                                                                                                                                            
        TXN.TENANTID ,                                                                                                                                                                                                                                                                                                                
        -- PER.PERIODSEQ,  Ver 1.0                                                                                                                                                                                                                                                                                                    
        i_periodseq,        -- Ver 1.0                                                                                                                                                                                                                                                                                                 
        --PER.NAME,   -- Ver 1.0                                                                                                                                                                                                                                                                                                      
        i_period,      -- Ver 1.0                                                                                                                                                                                                                                                                                                      
        TXN.SALESORDERSEQ,                                                                                                                                                                                                                                                                                                            
        TXN.SALESTRANSACTIONSEQ,                                                                                                                                                                                                                                                                                                      
        ordtxn.orderid,                                                                                                                                                                                                                                                                                                               
        TXN.LINENUMBER,                                                                                                                                                                                                                                                                                                               
        TXN.SUBLINENUMBER,                                                                                                                                                                                                                                                                                                            
        ETYPE.EVENTTYPEID,                                                                                                                                                                                                                                                                                                            
        TXN.COMPENSATIONDATE,                                                                                                                                                                                                                                                                                                         
        TXN.ACCOUNTINGDATE,  -- Fecha que indica el ciclo de facturacion                                                                                                                                                                                                                                                              
        TXN.PRODUCTID as Producto,                                                                                                                                                                                                                                                                                                    
        TXN.GENERICATTRIBUTE1 as Tipo_Servicio,                                                                                                                                                                                                                                                                                       
        TXN.GENERICATTRIBUTE2 as Nombre_Servicio,                                                                                                                                                                                                                                                                                     
        TXN.GENERICATTRIBUTE3 as Estado_GA3,                                                                                                                                                                                                                                                                                          
        TXN.GENERICATTRIBUTE4 as Estado_Liquidacion,                                                                                                                                                                                                                                                                                  
        TXN.GENERICATTRIBUTE5 As Motivo_Resultado,                                                                                                                                                                                                                                                                                    
        TXN.GENERICATTRIBUTE6,                                                                                                                                                                                                                                                                                                        
        TXN.GENERICATTRIBUTE7,                                                                                                                                                                                                                                                                                                        
        TXN.GENERICATTRIBUTE8 As IDMARCA,                                                                                                                                                                                                                                                                                             
        TXN.GENERICATTRIBUTE9 As IDMODELO,                                                                                                                                                                                                                                                                                            
        TXN.GENERICATTRIBUTE10,                                                                                                                                                                                                                                                                                                       
        TXN.GENERICATTRIBUTE11,                                                                                                                                                                                                                                                                                                       
        TXN.GENERICATTRIBUTE12,                                                                                                                                                                                                                                                                                                       
        TXN.GENERICATTRIBUTE13,                                                                                                                                                                                                                                                                                                       
        TXN.GENERICATTRIBUTE14,                                                                                                                                                                                                                                                                                                       
        TXN.GENERICATTRIBUTE15,                                                                                                                                                                                                                                                                                                       
        TXN.GENERICATTRIBUTE16,                                                                                                                                                                                                                                                                                                       
        TXN.GENERICATTRIBUTE17,                                                                                                                                                                                                                                                                                                       
        TXN.GENERICATTRIBUTE18,                                                                                                                                                                                                                                                                                                       
        TXN.GENERICATTRIBUTE19 as Codigo_comercial,                                                                                                                                                                                                                                                                                   
        TXN.GENERICATTRIBUTE20 as Incidencia,                                                                                                                                                                                                                                                                                         
        TXN.GENERICATTRIBUTE21 as SubProducto,                                                                                                                                                                                                                                                                                        
        TXN.GENERICNUMBER1 as Duracion,                                                                                                                                                                                                                                                                                               
        TXN.GENERICNUMBER2 as Plazo,                                                                                                                                                                                                                                                                                                  
        TXN.GENERICNUMBER3 as Paquetizacion,                                                                                                                                                                                                                                                                                          
        TXN.GENERICDATE3 as Fecha_Firma,                                                                                                                                                                                                                                                                                              
        TXN.GENERICDATE4 as Fecha_Alta,                                                                                                                                                                                                                                                                                               
        TXN.GENERICDATE5 as Fecha_Baja,                                                                                                                                                                                                                                                                                               
        TXN.GENERICBOOLEAN2 as SS_Garantia,                                                                                                                                                                                                                                                                                           
        TXN.PONUMBER as Contrato,                                                                                                                                                                                                                                                                                                     
        TXN.DATASOURCE,                                                                                                                                                                                                                                                                                                               
        TXNADD.ADDRESS1 AS Calle ,                                                                                                                                                                                                                                                                                                    
        TXNADD.CITY  AS Municipio ,                                                                                                                                                                                                                                                                                                   
        TXNADD.STATE AS Provincia ,                                                                                                                                                                                                                                                                                                   
        TXNADD.POSTALCODE as Codigo_Postal,                                                                                                                                                                                                                                                                                           
        TXNADD.INDUSTRY as Latitud,                                                                                                                                                                                                                                                                                                   
        TXNADD.GEOGRAPHY as Longitud,                                                                                                                                                                                                                                                                                                 
        TXNASS.POSITIONNAME,                                                                                                                                                                                                                                                                                                          
        TXNASS.GENERICATTRIBUTE1 as Comercial,                                                                                                                                                                                                                                                                                        
        TXNASS.GENERICATTRIBUTE2 as UsuarioCRM,                                                                                                                                                                                                                                                                                       
        TXNASS.GENERICNUMBER1 as Calidad_Tecnica_Gas,                                                                                                                                                                                                                                                                                 
        TXNASS.GENERICNUMBER2 as Calidad_Tecnica_Luz,                                                                                                                                                                                                                                                                                 
        etxn0.GENERICATTRIBUTE4 as FechaMaximaInicial,                                                                                                                                                                                                                                                                                
        etxn0.GENERICATTRIBUTE5 as Fecha_Validacion,                                                                                                                                                                                                                                                                                  
        etxn0.GENERICATTRIBUTE6 as FechaMaxima,                                                                                                                                                                                                                                                                                       
        etxn0.GENERICATTRIBUTE7 as InicioTrabajos,                                                                                                                                                                                                                                                                                    
        etxn0.GENERICATTRIBUTE8 as FinTrabajos,                                                                                                                                                                                                                                                                                       
        etxn0.GENERICATTRIBUTE9 as FechaSolicitdaCliente,                                                                                                                                                                                                                                                                             
        etxn0.GENERICATTRIBUTE10 as FechaHora_Apertura,                                                                                                                                                                                                                                                                               
        etxn0.GENERICATTRIBUTE11 as Fecha_Prevista,                                                                                                                                                                                                                                                                                   
        etxn0.GENERICATTRIBUTE12 as FormaPago,                                                                                                                                                                                                                                                                                        
        etxn0.GENERICATTRIBUTE13 as Num_Pedido_CRM,                                                                                                                                                                                                                                                                                   
        etxn0.GENERICATTRIBUTE14 as Num_Contrato_SVE,                                                                                                                                                                                                                                                                                 
        etxn0.GENERICATTRIBUTE15 as Tarifa,                                                                                                                                                                                                                                                                                           
        etxn0.GENERICATTRIBUTE16 as EmpresaEntrante,                                                                                                                                                                                                                                                                                  
        etxn0.GENERICATTRIBUTE17 as ComercializadoraSal,                                                                                                                                                                                                                                                                              
        etxn0.GENERICDATE3 as Fecha_Plataforma,                                                                                                                                                                                                                                                                                       
        etxn0.GENERICDATE4 as Fecha_Registro,                                                                                                                                                                                                                                                                                         
        etxn0.GENERICBOOLEAN1 as Hidden_Firma,                                                                                                                                                                                                                                                                                        
        etxn0.GENERICNUMBER1 as Num_Validaciones,                                                                                                                                                                                                                                                                                     
        etxn0.GENERICNUMBER2 as Num_Insistencias,                                                                                                                                                                                                                                                                                     
        etxn0.GENERICNUMBER3 as Num_Insistencias_App,                                                                                                                                                                                                                                                                                 
        etxn0.GENERICNUMBER4 as Num_CambiosNoLocalizado,                                                                                                                                                                                                                                                                              
        etxn0.GENERICNUMBER5 as Num_FueraPlazoCLiente,                                                                                                                                                                                                                                                                                
        TXN.PROCESSINGUNITSEQ,                                                                                                                                                                                                                                                                                                        
  -- MPR nuevo campo cups para cuadre de liq.                                                                                                                                                                                                                                                                                         
  TXN.ALTERNATEORDERNUMBER AS CUPS,                                                                                                                                                                                                                                                                                                   
  TXN.GENERICATTRIBUTE24 AS PEDIDO_CRM,                                                                                                                                                                                                                                                                                               
  ETXN0.GENERICATTRIBUTE3 as Motivo_BAJA                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                      
    FROM cs_salestransaction txn                                                                                                                                                                                                                                                                                                      
  INNER JOIN cs_salesorder ordtxn                                                                                                                                                                                                                                                                                                     
   ON txn.salesorderseq = ordtxn.salesorderseq                                                                                                                                                                                                                                                                                        
   AND ordtxn.removedate = v_eot                                                                                                                                                                                                                                                                                                      
   AND txn.tenantid = v_tenantid                                                                                                                                                                                                                                                                                                       
   AND ordtxn.processingunitseq = txn.processingunitseq                                                                                                                                                                                                                                                                               
   AND txn.compensationdate BETWEEN v_periodstartdate AND v_periodenddate                                                                                                                                                                                                                                                             
   AND txn.modelseq = 0                                                                                                                                                                                                                                                                                                               
   AND txn.processingunitseq = i_processingUnitSeq                                                                                                                                                                                                                                                                                     
   AND ordtxn.tenantid = txn.tenantid                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                      
  INNER JOIN cs_eventtype etype                                                                                                                                                                                                                                                                                                       
   ON txn.eventtypeseq = etype.datatypeseq                                                                                                                                                                                                                                                                                            
   AND etype.removedate = v_eot                                                                                                                                                                                                                                                                                                       
   AND txn.tenantid = etype.tenantid                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                      
  LEFT JOIN cs_gasalestransaction etxn0                                                                                                                                                                                                                                                                                               
   ON txn.salestransactionseq = etxn0.salestransactionseq                                                                                                                                                                                                                                                                             
   AND etxn0.tenantid = txn.tenantid                                                                                                                                                                                                                                                                                                  
   AND txn.processingunitseq = etxn0.processingunitseq                                                                                                                                                                                                                                                                                
   AND etxn0.pagenumber = 0                                                                                                                                                                                                                                                                                                           
   AND etxn0.compensationdate = txn.compensationdate                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                      
  LEFT JOIN                                                                                                                                                                                                                                                                                                                           
   (SELECT *                                                                                                                                                                                                                                                                                                                          
    FROM cs_transactionaddress txnaddress                                                                                                                                                                                                                                                                                             
    INNER JOIN cs_addresstype addtype                                                                                                                                                                                                                                                                                                 
     ON txnaddress.addresstypeseq = addtype.addresstypeseq                                                                                                                                                                                                                                                                            
     AND addtype.addresstypeid = 'BILLTO'                                                                                                                                                                                                                                                                                             
   ) txnadd                                                                                                                                                                                                                                                                                                                           
   ON txn.salestransactionseq = txnadd.salestransactionseq                                                                                                                                                                                                                                                                            
   AND txn.processingunitseq = txnadd.processingunitseq                                                                                                                                                                                                                                                                               
   AND txnadd.tenantid = txn.tenantid                                                                                                                                                                                                                                                                                                 
   AND txn.compensationdate = txnadd.compensationdate                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                      
  LEFT JOIN cs_transactionassignment txnass                                                                                                                                                                                                                                                                                           
   ON txn.salestransactionseq = txnass.salestransactionseq                                                                                                                                                                                                                                                                            
   AND txn.processingunitseq = txnass.processingunitseq                                                                                                                                                                                                                                                                               
   AND txnass.tenantid = txn.tenantid                                                                                                                                                                                                                                                                                                 
   AND txn.compensationdate = txnass.compensationdate                                                                                                                                                                                                                                                                                 
   AND txnass.setnumber > 0                                                                                                                                                                                                                                                                                                           
 ;
        
	CALL LIB_GLOBAL_ENDESA:WRITE_DEBUG(v_tenantid,v_permisos_log, v_proc_name,'Fin Carga de la tabla SMM_TXT_TEMP: '|| ::ROWCOUNT || ' filas.', v_log_count, v_idproceso, 'info');

    


    
  

	-- CALL EXT.SMM_SP_Z_CTRL_INF(v_contador_ctrl_inf, v_num_ejecucion, v_proc_name, v_finicio, current_timestamp, NULL);
	
	
	CALL LIB_GLOBAL_ENDESA:WRITE_DEBUG(v_tenantid,v_permisos_log, v_proc_name, 'Fin procedimiento', v_log_count, v_idproceso, 'info');
end;